languages_colors = {
    'C++': 'lightpink',
    'C#': 'lightblue',
    'Java': 'brown',
    'Ruby': 'red',
    'Pascal': 'lightpink',
    'Java Script': 'lightgreen',
    'Swift': 'lightyellow',
    '1C': 'purple',
    'Rust': 'pink',
    'PHP': 'blue',
    'Scala': 'red',
    'Python': 'green',
    'Не распознано': 'white'
}

language_keywords = {
    'C++': [
        '#include', 'std::cout <<', 'std::cin >>', 'std::', 'void', 'int', 'return',
        'if', 'else', 'for', 'while', 'class', 'public', 'private', 'using',
        'namespace', '->', '{', '}', '//'],

    'C#': [
        'using', 'namespace', 'class', 'public', 'private', 'static', 'void', 'int',
        'Console.WriteLine', 'Console.ReadLine()', 'return', 'if', 'else', 'new',
        'foreach', '=>', '//'],

    'Java': [
        'import', 'public', 'class', 'static', 'void', 'int', 'System.out.println',
        'System.in.read', 'this', 'new', 'return', 'if', 'else', 'for', 'while',
        'extends', 'implements', '//'],

    'Java Script': [
        'function', 'let', 'var', 'const', 'console.log', 'prompt', 'return',
        'this', 'if', 'else', 'for', 'while', '=>', 'class', '//'],

    'Ruby': [
        'def', 'puts', 'gets', 'return', 'self', 'class', 'begin', 'end',
        'if', 'else', 'elsif', 'unless', 'yield', 'do', 'then', 'rescue',
        'module', 'require', '#'],

    'Pascal': [
        'program', 'var', 'begin', 'end', 'writeln', 'readln', 'procedure',
        'function', 'integer', 'real', 'if', 'then', 'else', ':=', '//'],

    'Swift': [
        'import', 'func', 'let', 'var', 'print', 'readLine()', 'self', 'return',
        'if', 'else', 'guard', 'class', 'struct', 'enum', 'in', '{', '}', '//'],

    'Rust': [
        'fn', 'let', 'mut', 'println!', 'self', 'return', 'if', 'else',
        'loop', 'match', 'use', 'impl', 'enum', 'struct', '|', '{', '}', '//'],

    'Scala': [
        'def', 'val', 'var', 'println', 'class', 'object', 'trait', 'if', 'else',
        'match', 'case', '=>', 'this', 'return', '{', '}', '//'],

    '1C': [
        'Процедура', 'Функция', 'КонецПроцедуры', 'Перем', 'Если', 'Тогда',
        'Иначе', 'Для', 'Каждого', 'Из', 'Цикл', 'Пока', 'Сообщить',
        'ЭтотОбъект', 'КонецЦикла', 'КонецЕсли', '//'],

    'PHP': [
        '<?php', 'echo', 'readline', 'function', '$this', '$', 'return', 'if',
        'else', 'true', 'false', 'null', 'isset', 'empty', 'foreach', 'require',
        '//'],

    'Python': [
        'def', 'print', 'input', 'import', 'class', 'self',
        'lambda', 'if', 'else', 'elif', 'for', 'while',
        'return', 'try', 'except', 'with', 'as', 'from', '#']}

translation_rules = {

    ('Python', 'C++'): {
        'def': 'void',
        'print': 'std::cout <<',
        'input': 'std::cin >>',
        'self': 'this',
        'lambda': '[]()',
        '#': '//',
        ':': '{',
        'return': 'return',
        'True': 'true',
        'False': 'false'},

    ('Python', 'Java'): {
        'def': 'public void',
        'print': 'System.out.println',
        'input': 'Scanner.nextLine()',
        'self': 'this',
        'lambda': '->',
        '#': '//',
        'return': 'return',
        'True': 'true',
        'False': 'false'},

    ('Python', 'Java Script'): {
        'def': 'function',
        'print': 'console.log',
        'input': 'prompt',
        'self': 'this',
        'lambda': '()=>',
        '#': '//',
        'return': 'return'},

    ('Python', 'C#'): {
        'def': 'void',
        'print': 'Console.WriteLine',
        'input': 'Console.ReadLine()',
        'self': 'this',
        'lambda': '=>',
        '#': '//',
        'return': 'return'},

    ('Python', 'Ruby'): {
        'def': 'def',
        'print': 'puts',
        'input': 'gets',
        'self': 'self',
        'lambda': '->',
        '#': '#',
        ':': '',
        'return': 'return'},

    ('Python', 'Swift'): {
        'def': 'func',
        'print': 'print',
        'input': 'readLine()',
        'self': 'self',
        'lambda': 'in',
        '#': '//',
        'return': 'return'},

    ('Python', 'Rust'): {
        'def': 'fn',
        'print': 'println!',
        'input': 'stdin',
        'self': 'self',
        'lambda': '|x|',
        '#': '//',
        'return': 'return'},

    ('Python', 'Scala'): {
        'def': 'def',
        'print': 'println',
        'input': 'scala.io.StdIn.readLine()',
        'self': 'this',
        'lambda': '=>',
        '#': '//',
        'return': 'return'},

    ('Python', 'Pascal'): {
        'def': 'procedure',
        'print': 'writeln',
        'input': 'readln',
        'self': '',
        '#': '//',
        'return': 'exit'},

    ('Python', '1C'): {
        'def': 'Процедура',
        'print': 'Сообщить',
        'input': '',
        'self': 'ЭтотОбъект',
        '#': '//',
        'return': ''},

    ('Python', 'PHP'): {
        'def': 'function',
        'print': 'echo',
        'input': 'readline',
        'self': '$this',
        'lambda': 'function',
        '#': '//',
        'True': 'true',
        'False': 'false',
        'None': 'null',
        'return': 'return'},

    ('C++', 'Java'): {
        '#include': 'import',
        'std::cout <<': 'System.out.println',
        'std::cin >>': 'System.in.read',
        'std::': '',
        'void': 'public void',
        'int': 'int',
        'return': 'return',
        'if': 'if',
        'else': 'else',
        'for': 'for',
        'while': 'while',
        'class': 'class',
        'public': 'public',
        'private': 'private',
        'using': 'import',
        'namespace': 'package',
        '->': '->',
        '//': '//',
        '{': '{',
        '}': '}'},

    ('C++', 'C#'): {
        '#include': 'using',
        'std::cout <<': 'Console.WriteLine',
        'std::cin >>': 'Console.ReadLine()',
        'std::': '',
        'void': 'void',
        'int': 'int',
        'return': 'return',
        'if': 'if',
        'else': 'else',
        'for': 'for',
        'while': 'while',
        'class': 'class',
        'public': 'public',
        'private': 'private',
        'using': 'using',
        'namespace': 'namespace',
        '->': '=>',
        '//': '//',
        '{': '{',
        '}': '}'},

    ('C++', 'Java Script'): {
        'std::cout <<': 'console.log',
        'std::cin >>': 'prompt',
        'void': 'function',
        'int': 'let',
        'return': 'return',
        'if': 'if',
        'else': 'else',
        'for': 'for',
        'while': 'while',
        '->': '=>',
        '//': '//',
        '{': '{',
        '}': '}'},

    ('C++', 'Ruby'): {
        'std::cout <<': 'puts',
        'std::cin >>': 'gets',
        'void': 'def',
        'int': '',
        'return': 'return',
        'if': 'if',
        'else': 'else',
        'for': 'for',
        'while': 'while',
        'class': 'class',
        'public': '',
        'private': '',
        '->': '',
        '//': '#',
        '{': '',
        '}': 'end'},

    ('C++', 'Pascal'): {
        'std::cout <<': 'writeln',
        'std::cin >>': 'readln',
        'void': 'procedure',
        'int': 'integer',
        'return': 'exit',
        'if': 'if',
        'else': 'else',
        'for': 'for',
        'while': 'while',
        'begin': 'begin',
        'end': 'end',
        'class': 'type',
        '//': '//',
        '{': 'begin',
        '}': 'end'},

    ('C++', 'Swift'): {
        'std::cout <<': 'print',
        'std::cin >>': 'readLine()',
        'void': 'func',
        'int': 'Int',
        'return': 'return',
        'if': 'if',
        'else': 'else',
        'for': 'for',
        'while': 'while',
        'class': 'class',
        '{': '{',
        '}': '}',
        '//': '//'},

    ('C++', 'Rust'): {
        '#include': 'use',
        'std::cout <<': 'println!',
        'std::cin >>': '',
        'void': 'fn',
        'int': 'i32',
        'return': 'return',
        'if': 'if',
        'else': 'else',
        'for': 'for',
        'while': 'while',
        'class': 'struct',
        '->': '->',
        'std::': '',
        '{': '{',
        '}': '}',
        '//': '//'},

    ('C++', 'Scala'): {
        'std::cout <<': 'println',
        'std::cin >>': '',
        'void': 'def',
        'int': 'Int',
        'return': 'return',
        'if': 'if',
        'else': 'else',
        'for': 'for',
        'while': 'while',
        'class': 'class',
        '->': '=>',
        '{': '{',
        '}': '}',
        '//': '//'},

    ('C++', '1C'): {
        'std::cout <<': 'Сообщить',
        'std::cin >>': '',
        'void': 'Процедура',
        'int': 'Число',
        'return': '',
        'if': 'Если',
        'else': 'Иначе',
        'for': 'Для',
        'while': 'Пока',
        'class': '',
        '{': '',
        '}': '',
        '//': '//'},

    ('Java', 'C++'): {
        'import': '#include',
        'System.out.println': 'std::cout <<',
        'System.in.read': 'std::cin >>',
        'public void': 'void',
        'int': 'int',
        'return': 'return',
        'if': 'if',
        'else': 'else',
        'for': 'for',
        'while': 'while',
        'class': 'class',
        'public': 'public',
        'private': 'private',
        'this': 'this',
        '//': '//',
        '{': '{',
        '}': '}'},

    ('Java', 'C++'): {
        'import': '#include',
        'System.out.println': 'std::cout <<',
        'System.in.read': 'std::cin >>',
        'public void': 'void',
        'int': 'int',
        'return': 'return',
        'if': 'if',
        'else': 'else',
        'for': 'for',
        'while': 'while',
        'class': 'class',
        'public': 'public',
        'private': 'private',
        'this': 'this',
        '//': '//',
        '{': '{',
        '}': '}'},

    ('Java', 'C#'): {
        'import': 'using',
        'System.out.println': 'Console.WriteLine',
        'System.in.read': 'Console.ReadLine()',
        'public void': 'void',
        'int': 'int',
        'return': 'return',
        'if': 'if',
        'else': 'else',
        'for': 'for',
        'while': 'while',
        'class': 'class',
        'public': 'public',
        'private': 'private',
        'this': 'this',
        '//': '//',
        '{': '{',
        '}': '}'},

    ('Java', 'Java Script'): {
        'System.out.println': 'console.log',
        'System.in.read': 'prompt',
        'public void': 'function',
        'int': 'let',
        'return': 'return',
        'if': 'if',
        'else': 'else',
        'for': 'for',
        'while': 'while',
        'this': 'this',
        '//': '//',
        '{': '{',
        '}': '}'},

    ('Java', 'Ruby'): {
        'System.out.println': 'puts',
        'System.in.read': 'gets',
        'public void': 'def',
        'int': '',
        'return': 'return',
        'if': 'if',
        'else': 'else',
        'for': 'for',
        'while': 'while',
        'this': 'self',
        '//': '#',
        '{': '',
        '}': 'end'},

    ('Java', 'Pascal'): {
        'System.out.println': 'writeln',
        'System.in.read': 'readln',
        'public void': 'procedure',
        'int': 'integer',
        'return': 'exit',
        'if': 'if',
        'else': 'else',
        'for': 'for',
        'while': 'while',
        'class': 'type',
        '//': '//',
        '{': 'begin',
        '}': 'end'},

    ('Java', 'Swift'): {
        'System.out.println': 'print',
        'System.in.read': 'readLine()',
        'public void': 'func',
        'int': 'Int',
        'return': 'return',
        'if': 'if',
        'else': 'else',
        'for': 'for',
        'while': 'while',
        'class': 'class',
        '//': '//',
        '{': '{',
        '}': '}'},

    ('Java', 'Rust'): {
        'System.out.println': 'println!',
        'System.in.read': '',  #доп настройка
        'public void': 'fn',
        'int': 'i32',
        'return': 'return',
        'if': 'if',
        'else': 'else',
        'for': 'for',
        'while': 'while',
        'class': 'struct',
        '//': '//',
        '{': '{',
        '}': '}'},

    ('Java', 'Scala'): {
        'System.out.println': 'println',
        'System.in.read': 'scala.io.StdIn.readLine()',
        'public void': 'def',
        'int': 'Int',
        'return': 'return',
        'if': 'if',
        'else': 'else',
        'for': 'for',
        'while': 'while',
        'this': 'this',
        'class': 'class',
        '//': '//',
        '{': '{',
        '}': '}'},

    ('Java', '1C'): {
        'System.out.println': 'Сообщить',
        'System.in.read': '',
        'public void': 'Процедура',
        'int': 'Число',
        'return': '',
        'if': 'Если',
        'else': 'Иначе',
        'for': 'Для',
        'while': 'Пока',
        '//': '//',
        '{': '',
        '}': ''},

    ('C#', 'C++'): {
        'using': '#include',
        'Console.WriteLine': 'std::cout <<',
        'Console.ReadLine()': 'std::cin >>',
        'void': 'void',
        'int': 'int',
        'return': 'return',
        'if': 'if',
        'else': 'else',
        'for': 'for',
        'while': 'while',
        'class': 'class',
        'public': 'public',
        'private': 'private',
        'this': 'this',
        '=>': '->',
        '//': '//',
        '{': '{',
        '}': '}'},

    ('C#', 'Java'): {
        'using': 'import',
        'Console.WriteLine': 'System.out.println',
        'Console.ReadLine()': 'System.in.read',
        'void': 'public void',
        'int': 'int',
        'return': 'return',
        'if': 'if',
        'else': 'else',
        'for': 'for',
        'while': 'while',
        'class': 'class',
        'public': 'public',
        'private': 'private',
        'this': 'this',
        '=>': '->',
        '//': '//',
        '{': '{',
        '}': '}'},

    ('C#', 'Java Script'): {
        'Console.WriteLine': 'console.log',
        'Console.ReadLine()': 'prompt',
        'void': 'function',
        'int': 'let',
        'return': 'return',
        'if': 'if',
        'else': 'else',
        'for': 'for',
        'while': 'while',
        '=>': '=>',
        'this': 'this',
        '//': '//',
        '{': '{',
        '}': '}'},

    ('C#', 'Ruby'): {
        'Console.WriteLine': 'puts',
        'Console.ReadLine()': 'gets',
        'void': 'def',
        'int': '',
        'return': 'return',
        'if': 'if',
        'else': 'else',
        'for': 'for',
        'while': 'while',
        'this': 'self',
        '//': '#',
        '{': '',
        '}': 'end'},

    ('C#', 'Pascal'): {
        'Console.WriteLine': 'writeln',
        'Console.ReadLine()': 'readln',
        'void': 'procedure',
        'int': 'integer',
        'return': 'exit',
        'if': 'if',
        'else': 'else',
        'for': 'for',
        'while': 'while',
        '//': '//',
        '{': 'begin',
        '}': 'end'},

    ('C#', 'Swift'): {
        'Console.WriteLine': 'print',
        'Console.ReadLine()': 'readLine()',
        'void': 'func',
        'int': 'Int',
        'return': 'return',
        'if': 'if',
        'else': 'else',
        'for': 'for',
        'while': 'while',
        'this': 'self',
        '//': '//',
        '{': '{',
        '}': '}'},

    ('C#', 'Rust'): {
        'Console.WriteLine': 'println!',
        'Console.ReadLine()': '',
        'void': 'fn',
        'int': 'i32',
        'return': 'return',
        'if': 'if',
        'else': 'else',
        'for': 'for',
        'while': 'while',
        'this': 'self',
        '=>': '->',
        '//': '//',
        '{': '{',
        '}': '}'},

    ('C#', 'Scala'): {
        'Console.WriteLine': 'println',
        'Console.ReadLine()': 'scala.io.StdIn.readLine()',
        'void': 'def',
        'int': 'Int',
        'return': 'return',
        'if': 'if',
        'else': 'else',
        'for': 'for',
        'while': 'while',
        'this': 'this',
        '=>': '=>',
        '{': '{',
        '}': '}',
        '//': '//'},

    ('C#', '1C'): {
        'Console.WriteLine': 'Сообщить',
        'Console.ReadLine()': '',
        'void': 'Процедура',
        'int': 'Число',
        'return': '',
        'if': 'Если',
        'else': 'Иначе',
        'for': 'Для',
        'while': 'Пока',
        'this': 'ЭтотОбъект',
        '{': '',
        '}': '',
        '//': '//'},

    ('Rust', 'C++'): {
        'println!': 'std::cout <<',
        'fn': 'void',
        'let': 'int',
        'mut': '',
        'return': 'return',
        'if': 'if',
        'else': 'else',
        'for': 'for',
        'while': 'while',
        'loop': 'while(true)',
        'match': 'switch',
        'struct': 'class',
        'enum': 'enum',
        'use': '#include',
        'impl': '',
        '|': '',
        '{': '{',
        '}': '}',
        '//': '//'},

    ('Rust', 'Java'): {
        'println!': 'System.out.println',
        'fn': 'public void',
        'let': 'int',
        'mut': '',
        'return': 'return',
        'if': 'if',
        'else': 'else',
        'for': 'for',
        'while': 'while',
        'loop': 'while(true)',
        'match': 'switch',
        'struct': 'class',
        'enum': 'enum',
        'use': 'import',
        'impl': '',
        '|': '',
        '{': '{',
        '}': '}',
        '//': '//'},

    ('Rust', 'C#'): {
        'println!': 'Console.WriteLine',
        'fn': 'void',
        'let': 'int',
        'mut': '',
        'return': 'return',
        'if': 'if',
        'else': 'else',
        'for': 'for',
        'while': 'while',
        'loop': 'while(true)',
        'match': 'switch',
        'struct': 'class',
        'enum': 'enum',
        'use': 'using',
        'impl': '',
        '|': '',
        '{': '{',
        '}': '}',
        '//': '//'},

    ('Rust', 'Java Script'): {
        'println!': 'console.log',
        'fn': 'function',
        'let': 'let',
        'mut': '',
        'return': 'return',
        'if': 'if',
        'else': 'else',
        'for': 'for',
        'while': 'while',
        'loop': 'while(true)',
        'match': 'switch',
        'struct': 'class',
        'enum': 'enum',
        '|': '',
        '{': '{',
        '}': '}',
        '//': '//'},

    ('Rust', 'Ruby'): {
        'println!': 'puts',
        'fn': 'def',
        'let': '',
        'mut': '',
        'return': 'return',
        'if': 'if',
        'else': 'else',
        'for': 'for',
        'while': 'while',
        'loop': 'loop do',
        'match': 'case',
        'struct': 'class',
        '|': '',
        '{': '',
        '}': 'end',
        '//': '#'},

    ('Rust', 'Pascal'): {
        'println!': 'writeln',
        'fn': 'procedure',
        'let': 'var',
        'mut': '',
        'return': 'exit',
        'if': 'if',
        'else': 'else',
        'for': 'for',
        'while': 'while',
        'loop': 'while true do',
        'match': 'case',
        'struct': 'record',
        'enum': 'type',
        '|': '',
        '{': 'begin',
        '}': 'end',
        '//': '//'},

    ('Rust', 'Swift'): {
        'println!': 'print',
        'fn': 'func',
        'let': 'var',
        'mut': '',
        'return': 'return',
        'if': 'if',
        'else': 'else',
        'for': 'for',
        'while': 'while',
        'loop': 'while true',
        'match': 'switch',
        'struct': 'struct',
        'enum': 'enum',
        '|': '',
        '{': '{',
        '}': '}',
        '//': '//'},

    ('Rust', 'Scala'): {
        'println!': 'println',
        'fn': 'def',
        'let': 'var',
        'mut': '',
        'return': 'return',
        'if': 'if',
        'else': 'else',
        'for': 'for',
        'while': 'while',
        'loop': 'while(true)',
        'match': 'match',
        'struct': 'class',
        'enum': 'sealed trait',
        '|': '',
        '{': '{',
        '}': '}',
        '//': '//'},

    ('Rust', '1C'): {
        'println!': 'Сообщить',
        'fn': 'Процедура',
        'let': 'Перем',
        'mut': '',
        'return': '',
        'if': 'Если',
        'else': 'Иначе',
        'for': 'Для',
        'while': 'Пока',
        'loop': 'Пока Истина Цикл',
        'match': 'Выбор',
        'struct': '',
        'enum': '',
        '|': '',
        '{': '',
        '}': '',
        '//': '//'},

    }

